apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels: { app: db }
  template:
    metadata:
      labels: { app: db }
    spec:
      containers:
      - name: db
        image: docker.io/bitnami/postgresql:latest   # 👈 tag dispo
        env:
        - name: POSTGRESQL_USERNAME
          value: appuser
        - name: POSTGRESQL_PASSWORD
          value: apppass
        - name: POSTGRESQL_DATABASE
          value: appdb
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 5432
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
      volumes:
      - name: data
        emptyDir: {}
