apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels: { app: front }
  template:
    metadata:
      labels: { app: front }
    spec:
      containers:
      - name: front
        image: nginxinc/nginx-unprivileged:stable
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: false   # 👈 on désactive RO le temps de stabiliser
