apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels: { app: back }
  template:
    metadata:
      labels: { app: back }
    spec:
      containers:
      - name: back
        image: ghcr.io/traefik/whoami:latest
        args: ["--port=8080"]
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001        # 👈 satisfait runAsNonRoot même si l'image déclare USER root
